# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.04, name: 'TAG_0'}, # sized at 40mm
    {id: 1, size: 0.04, name: 'TAG_1'},
    {id: 2, size: 0.04, name: 'TAG_2'},
    {id: 3, size: 0.04, name: 'TAG_3'},
    {id: 4, size: 0.04, name: 'TAG_4'},
    {id: 5, size: 0.04, name: 'TAG_5'},
    {id: 6, size: 0.04, name: 'TAG_6'},
    # {id: 7, size: 0.04, name: 'TAG_7'},
    # {id: 8, size: 0.04, name: 'TAG_8'},
    # {id: 9, size: 0.04, name: 'TAG_9'},
    # {id: 10, size: 0.04, name: 'TAG_10'},
    # {id: 11, size: 0.04, name: 'TAG_11'},
    # {id: 12, size: 0.04, name: 'TAG_12'},
    # {id: 13, size: 0.04, name: 'TAG_13'},
    # {id: 14, size: 0.04, name: 'TAG_14'},
    # {id: 15, size: 0.04, name: 'TAG_15'},
    # {id: 16, size: 0.04, name: 'TAG_16'},
    # {id: 17, size: 0.04, name: 'TAG_17'},
    # {id: 18, size: 0.04, name: 'TAG_18'},
    # {id: 19, size: 0.04, name: 'TAG_19'},
    # {id: 20, size: 0.04, name: 'TAG_20'},
    # {id: 21, size: 0.04, name: 'TAG_21'},
    # {id: 22, size: 0.04, name: 'TAG_22'},
    # {id: 23, size: 0.04, name: 'TAG_23'},
    # {id: 24, size: 0.04, name: 'TAG_24'}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]
